import { PropertyListing } from '../types';

export const MOCK_PROPERTIES: PropertyListing[] = [
    {
        id: 'prop_1',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        imageUrls: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80'],
        title: 'Modern Apartment with Ocean View',
        description: 'Beautiful 2 bedroom apartment featuring sweeping ocean views and modern amenities.',
        price: 350000,
        propertyType: 'apartment',
        bedrooms: 2,
        bathrooms: 2,
        squareMeters: 85,
        city: 'Miami',
        neighborhood: 'South Beach',
        address: '123 Ocean Drive',
        contactPhone: '+1234567890',
        createdBy: 'agent_1',
        createdAt: Date.now(),
        status: 'active',
        operation: 'sale',
        features: ['Ocean View', 'Gym', 'Security', 'Pool'],
        isPromoted: true,
    },
    {
        id: 'prop_2',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
        imageUrls: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'],
        title: 'Luxury Villa in the Hills',
        description: 'A stunning 4 bedroom villa with a private pool and large garden.',
        price: 1200000,
        propertyType: 'home',
        bedrooms: 4,
        bathrooms: 3,
        squareMeters: 250,
        city: 'Los Angeles',
        neighborhood: 'Beverly Hills',
        address: '456 Hill Drive',
        contactPhone: '+1987654321',
        createdBy: 'agent_2',
        createdAt: Date.now() - 86400000,
        status: 'active',
        operation: 'sale',
        features: ['Private Pool', 'Garden', 'Garage', 'Security'],
        isPromoted: false,
    },
    {
        id: 'prop_3',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        imageUrls: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80'],
        title: 'Cozy Downtown Loft',
        description: 'Perfect for young professionals. High ceilings and exposed brick.',
        price: 2500,
        propertyType: 'apartment',
        bedrooms: 1,
        bathrooms: 1,
        squareMeters: 65,
        city: 'New York',
        neighborhood: 'SoHo',
        address: '789 Broadway',
        contactPhone: '+1122334455',
        createdBy: 'agent_1',
        createdAt: Date.now() - 172800000,
        status: 'active',
        operation: 'rent',
        features: ['Elevator', 'Security', 'Gym'],
        isPromoted: true,
    }
];
